package content.region.misthalin.lumbridge.plugin.gnomecopter.sign

import core.game.world.map.Location
import core.tools.RED
import shared.consts.Quests

enum class GnomecopterSignDefinition(override val location: Location, override val info: Array<String>, override val scrollable: Boolean): InformationSign
{
    //Lumbridge
    ENTRANCE(Location(3161, 3331, 0) , arrayOf("Welcome to Gnomecopter", "Tours: the unique flying", "experience!", "", "If you're a new flier, talk to", "<col=FF0000>Hieronymus</col> and prepare to be", "amazed by this triumph of", "gnomic engineering.", "", "", "Warning: all riders must be at", "least 2ft, 6ins tall."), false),

    //Burgh de Rott
    GENERAL_STORE(Location(2153, 5431, 0), arrayOf("This player is stocking the", "general store with useful", "items.", "", "Down in swampy Morytania,", "the locals' idea of a tasty", "meal is a giant snail, so the", "shop needs plenty of those.", "There's also plenty of demand", "for basic tools such as axes", "and tinderboxes."), false),
    GLOBAL_SIGN(Location(2160, 5427, 0), arrayOf("Vampyres can only be hunt", "with silver weapons, such as", "blessed silver sickles and", "silver crossbow bolts.", "", "Once they are sufficiently", "weakened, they can be", "finished off with the use of a", "special silver rod and a dose", "of a certain kind of potion.", "You'll learn all about fighting", "vampyres if you complete the", "${RED}${Quests.IN_AID_OF_THE_MYREQUE}</col> quest."),false),
    FURNACE_SIGN(Location(2162, 5409, 0), arrayOf("The furnace in burgh de Rott", "needs to be repaired and", "stocked with coal before it", "can be used.", "", "This player is using it to", "make a special rod out of a", "silver and mithril alloy, to help", "when fighting vampyres."),false),
    BANK_SIGN(Location(2140, 5408, 0), arrayOf("Every town needs a bank.", "The bank in Burgh de Rott is", "badly in need of repair, so", "this player is fixing it. The", "hole in the bank's wall also", "needs patching."), false),

    //Burthorpe
    CORRIDOR_SIGN(Location(2399, 5396, 0), arrayOf("This corridor leads to a", "selection of waiting rooms,", "one for each boardgame.", "", "Players wishing to play a", "specific game can wait in", "the appropriate room,", "making it easier for them", "to arrange a match.", "", "Additional waiting rooms", "are provided upstairs for", "the sole use of players", "with high ranks in the", "boardgames. For the elite", "gamer, that's the place", "where any challenge will be", "from a worthy foe."), true),

    //Castle Wars
    CENTER_ISLAND_SIGN(Location(2028, 5409, 0), arrayOf("In the centre of this island,", "trapdoors lead down into the", "tunnels below. The tunnels", "lead into the basements of", "the two castles.", "", "Players may collapse the", "tunnels, forcing the enemy to", "mine through the rubble in", "order to proceed."), false),
    WALL_SIGN(Location(2039, 5397, 0), arrayOf("A determined player can scale", "the castle walls by deftly", "throwing a rope over the", "battlements, then climbing up.", "", "Of course, there's a high", "chance that someone up there", "will swiftly kill them."), false),
    MAIN_SIGN(Location.create(2023, 5392, 0), arrayOf("~ What is this? ~", "This is the storeroom of", "the Zamorak castle. Players", "collect equipment from here", "before running into the", "fray", "", "They also have to fight off", "any Saradomin fighters", "who've breached the castle.", "", "Under the area are", "tunnels that lead into the", "basements of the two", "castles. Players will often", "defend their tunnel by using", "a ${RED}pickaxe</col> to collapse the", "walls.", "", "The ${RED}barricades</col> can be used", "to block passageways. To", "get past a barricade,", "players can destroy it with", "their weapon, set it on fire", "or blow it up with an", "explosive potion.", "", "The ${RED}explosive potions</col> can", "also be used to blow up", "the enemy team's catapult", "and to clear rockslides in", "the tunnels under the", "area.", "", "${RED}Toolkits</col> can be used to", "repair catapults that have", "been blown up.", "", "Once a catapult's working,", "players are able to fire", "${RED}rocks</col> into the battlefield,", "damaging anyone who gets", "in the way.", "", "${RED}ropes</col> are handy when you", "want to climb up the", "enemy castle's walls."), true),
    MAIN_SIGN_NEXT_FLOOR(Location.create(2023, 5392, 0), arrayOf("~ What is this? ~", "This is the spawning room", "of the Saradomin castle.", "", "Players enter and exit the", "game through the round", "portal. They also reappear", "here if they die while", "playing Castle Wars. It's a", "safe minigame, so players", "don't lose any items when", "they die.", "", "The table in the corner of", "the room contains", "bandages. Players can take", "as many of these as they", "like to ."), true),
    MAIN_SIGN_SPAWN_ROOM_FLOOR(Location.create(2023, 5392, 0), arrayOf("This is the spawning room", "of the Saradomin castle.", "", "Players enter and exit the", "game through the round", "portal. They also reappear", "here if they die while", "playing Castle Wars. It's a", "safe minigame, so players", "don't lose any items when", "they die.", "", "The table in the corner of", "the room contains", "bandages. Players can take", "as many of these as they", "like to heal themselves", "when they're fighting.", "Bandages can also be used", "to heal team-mates."), true),
    MAIN_SIGN_ROOF_SARADOMIN_EXAMPLE_1(Location.create(2023, 5392, 0), arrayOf("~ What is this? ~", "This is the roof of the", "Saradomin castle. The blue", "flag is here at the", "beginning of the game and", "it stays here until one of", "the Zamorak team arrives", "to capture it.", "", "In this example, there are", "two Saradomin warriors", "standing guard, repelling all", "attempts to steal the flag.", "a ${RED}binding spell</col> on the flag-", "bearer, which prevents the", "bearer from walking for a", "few seconds. He also sets", "up a ${RED}barricade</col> to block the", "staircase.", "", "Although a second Zamorak", "warrior sets the barricade", "on fire to destroy it, he is", "successfully prevented from", "helping his friend to steal", "the flag."), true),
    CASTLE_WARS_ROOF_ZAMORAK(Location.create(2023, 5392, 0), arrayOf("This is the roof of the", "Zamorak castle. The red flag", "is here at the beginning of the", "game and it stays here until", "one of the Saradomin team", "arrives to capture it.", "", "In this example, the flag is", "stolen by a Saradomin", "warrior. The Zamorak", "defender pursues him,", "retrieves the flag when he", "dies, then brings it back here."), true),

    //Pest Control
    LANDER_SIGN(Location(2276, 5423, 0), arrayOf("These landers are used to", "transport players from the", "${RED}Void Knights' Outpost</col> to", "this battlefield.", "", "At the outpost there are", "three landers, each with a", "different Combat level", "requirement. Players must", "have ${RED}level 40 Combat to", "use this first boat, ${RED}level 70</col>", "to use the second and ${RED}level</col>", "${RED}100</col> to use the third.", "", "The higher-level landers", "visit islands containing", "tougher pests, where even", "the top players will have to", "hustle if they want to", "overcome the invading", "hordes.", "", "During the fight, players", "may use this lander to flee", "back to the Void Knights'", "Outpost, but who'd ever", "want to do that?"), true),
    CENTER_SIGN(Location(2281, 5410, 0), arrayOf("In the centre of the island,", "we find the Void Knight", "whose task it is to unshield", "and banish those portals of", "the pests.", "", "Although this area is", "surrounded by high walls,", "some of the pests can still", "sneak though to attack the", "Void Knight, especially", "these teleporting ${RED}shafters</col>. A", "tough band of players will", "usually station themselves", "around the central mound", "to kill anything that gets", "through.", "", "If the Void Knight dies, the", "game is lost."), true),
    PORTAL_SIGN(Location(2252, 5411, 0), arrayOf("Four ${RED}portals</col> open up on", "this island, spawning", "hordes of chaotic pests.", "", "When a portal first spawns,", "it will be surrounded by a", "strong ${RED}shield</col> that protects", "it from all attacks. The", "${RED}Void Knight</col> will use", "powerful magic to bring", "down the shields of the", "portals one by one, making", "them vulnerable to attack", "by players.", "", "A powerful team of players", "can usually be found", "roaming from portal to", "portal, using every weapon", "at their disposal to shut", "them down before the", "world is taken over by", "pests."), true),
    TOWER_SIGN(Location.create(2266, 5399, 0), arrayOf("Players will commonly", "ascend these towers to", "snipe at the enemies", "below.", "", "Of course, the ${RED}torchers</col> and", "${RED}defilers</col> are perfectly", "capable of shooting back", "and they'll very happily do", "this; however, so long as", "the pests can be distracted", "from shooting at the all-", "important ${RED}Void Knight</col>, it", "doesn't matter if a few", "players get slaughtered.", "", "${RED}Ravagers</col> will attempt to", "smash the gates down, so,", "if there's one heading for a", "gate, it's important that it is", "stepped before it can", "breach the fortress."), true),

    //Trollweiss & Rellekka
    RELLEKKA_EAGLES_SIGN(Location(2543, 5430, 1), arrayOf("In the icy mountain, a small", "cavern contains the lair of", "some giant eagles.", "", "After completing the ${RED}Eagles</col>", "${RED}Peak</col> quest, players may catch", "them with a rope and ride", "them to other eagle nests,", "around the world."), false),
    EAST_OF_TROLLWEISS_SIGN(Location(2543, 5422, 1), arrayOf("East of the Trollweiss and", "Rellekka Hunter area lies a", "range of snowy mountains", "populated by fearsome ice", "trolls and wolves. Players", "come here for the ${RED}Desert</col>", "${RED}Treasure</col> quest and to", "enter the insanely", "dangerous ${RED}God Wars</col>", "${RED}Dungeon</col>.", "", "Not all quests are just", "about fighting, however. In", "the ${RED}${Quests.TROLL_ROMANCE}</col> quest,", "players are challenged to", "help a particularly soppy", "troll gain the affections of", "their beloved. This involves", "building a sled and taking it", "for a ride down this", "mountain!"), true);
}